[project]
name = "openagv"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "openai>=2.15.0",
    "opentimelineio>=0.18.1",
    "pillow>=12.1.0",
    "semantic-kernel>=1.36.0",
]

[tool.pdoc]
output_directory = "docs"

[dependency-groups]
dev = [
    "pdoc>=16.0.0",
]
